version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/workspace
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}
            - deps-v1-

      - run:
          name: Install Dependencies
          command: make install-no-clean

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: make lint
          when: always

      - run:
          name: Tests
          command: make test
          when: always

      - run:
          name: Package functions
          command: make package
          when: always

      - run:
          name: Run bundlesize in our CI for testing
          command: make bundlesize

      - store_artifacts:
          path: artifacts

      - store_test_results:
          path: artifacts/test_results

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts/
            - lib/
            - node_modules/
  deploy:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/workspace
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - type: shell
      name: Deploy Package
      command: |
        if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
        then
          version=$(git log -1 --pretty=%B)
          VERSION_TO_PUBLISH=$version make deploy
        else
          echo "Not a release, skipping build"
        fi

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

